name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry and deps
        run: |
          pip install poetry==2.1.2
          poetry install --with dev

      - name: Lint (ruff & black)
        run: |
          poetry run ruff .
          poetry run black --check .

      - name: Type check (mypy)
        run: poetry run mypy ai_repo || true

      - name: Run tests
        run: poetry run pytest --cov=ai_repo --cov-report=term-missing
